# Site settings
baseURL = "https://tamuccc.netlify.com"
languageCode = "en-us"
title = "TAMU Collegiate Content Creators"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-125245351-1"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "TAMU Collegiate Content Creators"
  description = "We are a collective group of creators and innovators. Our mission is to be a fun place for creators to collaborate!"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "tamu-ccc-legacy-favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "TAMUCCC"
    subtitle = "Texas A&M Collegiate Content Creators"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "tamu-ccc-logo-small.png"

    [[params.navigation.links]]
      name = "Home"
      url = "https://tamuccc.com"

    [[params.navigation.links]]
      name = "Instagram"
      url = "https://instagram.com/TAMUCCC"

    [[params.navigation.links]]
      name = "Facebook"
      url = "https://facebook.com/TAMUCCC"

    [[params.navigation.links]]
      name = "Twitter"
      url = "https://twitter.com/TAMUCCC"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
#    [[params.navigation.button1]]
#      name = "Get Started"
#      url = "blogs"

    # Button Style 2
#    [[params.navigation.button2]]
#      name = "Log In"
#      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome, Creators"
    subtitle = "We are a collective group of creators and innovators. Our mission is to be a fun place for creators to collaborate!"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Youtube"
      subtitle = "We will post updates here"
      image = "youtube-image.jpg"
      url = "https://www.youtube.com/channel/UCKtxHe1zE0pMSzBhpOAHGlQ"

    [[params.tiles.showcase]]
      title = "GroupMe"
      subtitle = "Join the community!"
      image = "people-working-together.jpg"
      url = "https://groupme.com/join_group/39139534/J4X079"

    [[params.tiles.showcase]]
      title = "Twitter"
      subtitle = "Follow us on twitter"
      image = "twitter-photo.jpg"
      url = "https://twitter.com/TAMUCCC"

    [[params.tiles.showcase]]
      title = "Discord"
      subtitle = "Join our Discord server"
      image = "emoji-face.jpg"
      url = "https://discord.gg/UhgXdzT"

    # You can make more showcases by copy and pasting the code above

#  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Join our Facebook Page"
    subtitle = """CCC Stands for Collegiate Content Creators. We are a collective
     group of creators and innovators. Our main mission is to be a fun place
     where creators can collaborate and help each other out. If you have a
     YouTube, podcast, crest musics, or any other type of media this is the place
     for you. We are also working on some exciting projects including a
     documentary for Professor Rodney Hill, as well as building a state of the
     art studio. We have tons of ways for y’all to get involved and can’t wait
     to meet and collaborate with y’all! Please come to the meeting to learn
     more. If you can’t make it that’s ok! We still want you to be involved."""
    buttonText = "Get Started"
    url = "https://facebook.com/TAMUCCC"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "contact@tamuccc.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "contact@tamuccc.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(123) 456 7890"

    [[params.contact.address]]
    title = "Address"
    street = "Heep Laboratory Building 645 Lamar St."
    city = "College Station, TX 77840"
    country = "United States"

  # Footer section
  [params.footer]
    enable = true
    copyright = "TAMU Collegiate Content Creators"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/TAMUCCC"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/TAMUCCC"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/TAMUCCC"
      label = "Instagram"

    [[params.footer.social]]
      icon = "fa-comments"
      url = "https://groupme.com/join_group/39139534/J4X079"
      label = "GroupMe"

#    [[params.footer.social]]
#      icon = "fa-discord"
#      url = "https://discord.gg/UhgXdzT"
#      label = "Discord"

#    [[params.footer.social]]
#      icon = "fa-github"
#      url= "https://www.github.com"
#      label = "GitHub"

#    [[params.footer.social]]
#      icon = "fa-linkedin"
#      url= "https://www.linkedin.com"
#      label = "LinkedIn"

#    [[params.footer.quicklinks]]
#      text = "Design: "
#      url= "https://www.html5up.net"
#      alt = "HTML5 UP"
